#!/bin/bash

#SBATCH --job-name=nnunet_training  
#SBATCH --chdir=/work/phalempi      # modify with your paths
#SBATCH --output=/work/%u/%x-%j.log
#SBATCH --time=1080                 # modify with your time limit
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=7
#SBATCH --mem-per-cpu=60G
#SBATCH --mail-type=BEGIN,END       # modify with your mail preferences
#SBATCH -G nvidia-a100:1            # modify with your GPU preferences

##  activating  the virtual environment
source /home/phalempi/MPvenv/bin/activate # modify with your paths

## declaring the environment variable
export nnUNet_preprocessed="/data/bosys-nnunet/nnUNet_preprocessed" # modify with your path
export nnUNet_results="/work/phalempi/nnUNet_results" # modify with your path

## Run training with nnUNet native command
nnUNetv2_train 304 3d_fullres $SLURM_ARRAY_TASK_ID -tr nnUNetTrainer_betterIgnoreSampling